name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
    - name: Run tests
      run: cd freecad/Curves 
    - name: get freecad
      run: wget https://github.com/FreeCAD/FreeCAD/releases/download/weekly-2025.07.29/FreeCAD_weekly-2025.07.29-Linux-x86_64-py311.AppImage -O FreeCAD.AppImage && chmod +x FreeCAD.AppImage
    - name: Run tests
      run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          ./FreeCAD.AppImage -M `pwd` -t freecad.Curves.TestCurves